---
apiVersion: v1
kind: Namespace
metadata:
  name: llm-app
  labels:
    name: llm-app

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-config
  namespace: llm-app
data:
  OLLAMA_URL: "http://ollama-service:11434"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: llm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: llm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: omarhussein2111/ollama_email_service:latest
          ports:
            - containerPort: 8000
          env:
            - name: OLLAMA_URL
              valueFrom:
                configMapKeyRef:
                  name: llm-config
                  key: OLLAMA_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: llm-app
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: llm-app
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
